// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXqWvhsTQIPO-iSTgoB6sV5BcgL-zP2sM',
    appId: '1:401797842103:web:placeholder', // placeholder
    messagingSenderId: '401797842103',
    projectId: 'letschat-e73bf',
    authDomain: 'letschat-e73bf.firebaseapp.com',
    storageBucket: 'letschat-e73bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXqWvhsTQIPO-iSTgoB6sV5BcgL-zP2sM',
    appId: '1:401797842103:android:c3c21aaca9f6731e74b932',
    messagingSenderId: '401797842103',
    projectId: 'letschat-e73bf',
    storageBucket: 'letschat-e73bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXqWvhsTQIPO-iSTgoB6sV5BcgL-zP2sM',
    appId: '1:401797842103:ios:placeholder',
    messagingSenderId: '401797842103',
    projectId: 'letschat-e73bf',
    storageBucket: 'letschat-e73bf.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );
}
